### ISSUE TITLE
Add styled-components as dependency

### ISSUE THREAD

**Issue by adil14788** [arvind0598/better-first-issues#12]
Hello @arvind0598  , I was trying to run the project locally but I was unable to do the same
can you please help me with the dependencies I need to install to be able to run this project

**Comment by arvind0598** [comment]
What's the issue you're facing? If you have Node installed it should just be an `npm install` and an `npm run dev `

**Comment by adil14788** [comment]
![Screenshot (493)](https://user-images.githubusercontent.com/61096177/134971281-618cbbb3-47d8-4a06-a870-d034e2c7655a.png)

### styled-components dependency was not there 
so I did npn intall styled-components then it started working

**Comment by emmalearnscode** [comment]
I had the same issue. Do a separate npm i styled-components --save fixed it

**Comment by arvind0598** [comment]
Let me check on that. I suppose it worked for me without it because it might have been installed globally beforehand.

**Comment by adil14788** [comment]
> I had the same issue. Do a separate npm i styled-components --save fixed it

Thanks it worked for me as well

**Comment by adil14788** [comment]
> Let me check on that. I suppose it worked for me without it because it might have been installed globally beforehand.

Most probably yes

**Comment by arvind0598** [comment]
@emmalearnscode can you take this then? Seems like it'll just get covered within the PR for the other issues you picked up.

**Comment by emmalearnscode** [comment]
Sure. I will just add my package.json to the commit.

**Comment by arvind0598** [comment]
Fixed in #14
