### ISSUE TITLE
Avoid using `console` in code that runs on browser

### ISSUE THREAD

**Issue by adil14788** [arvind0598/better-first-issues#23]
I have found a console.log() statement in services/github/submit-query.ts, I think it not advisible to use console in the code that runs on the browse
![Screenshot (56)](https://user-images.githubusercontent.com/61096177/136462678-900fb931-e99e-4c6d-b79e-9c2b8fdb039a.png)
r

**Comment by arvind0598** [comment]
That code actually runs on the server. You shouldn't be seeing it on the browser console. Any chance you can send over a screenshot or something?
