### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by arvind0598** [arvind0598/better-first-issues#3]
There are a few issues with the README, on account of it being a template that I modified to suit the project's needs. Specifically, some of the links may not work (like both links in the License section), or an entire section may not make any sense (like the "Built With" and "License" section).

**Comment by adil14788** [comment]
> some of the links may not work (like both links in the License section)

@arvind0598 
Under License Section 
 **CC0 2.1 Universal** is working but **LICENSE.md** is not working

**Comment by adil14788** [comment]
Can I use this 
[CC License](https://github.com/santisoler/cc-licenses)

**Comment by arvind0598** [comment]
> Can I use this 
> 
> [CC License](https://github.com/santisoler/cc-licenses)

Hi Adil, that shouldn't be necessary. The issue here is that the file in this repository is named "LICENSE", not "LICENSE.md" 

The link in the README should point there instead.

**Comment by arvind0598** [comment]
Thanks for your help @adil14788
