### ISSUE TITLE
The badge should not render when there is no text passed to it.

### ISSUE THREAD

**Issue by arvind0598** [arvind0598/better-first-issues#4]
![image](https://user-images.githubusercontent.com/17570244/134673010-b539c567-88ca-4cef-85b7-627675c94e36.png)

The language of the repository might sometimes be null. In this case we should not be rendering the language badge at all.

This should be fixed by including the null check in components/repository.

**Comment by emmalearnscode** [comment]
I fixed this when I was working on repository card before I saw this separate issue. Pull request coming later this week.

**Comment by arvind0598** [comment]
That's great news, @emmalearnscode

**Comment by arvind0598** [comment]
Fixed in #14
