### ISSUE TITLE
Enhance the Repository Card

### ISSUE THREAD

**Issue by arvind0598** [arvind0598/better-first-issues#6]
The repository card currently contains the bare minimum amount of information. The component receives ALL the information that the Github Search API provides, its just not used right now. It would be useful to have a direct link and possibly restructure the card to make it more useful, including images would be nice too.

**Comment by emmalearnscode** [comment]
Can I take this issue and also work on the design of the card? I noticed the info is overflowing the card in some places, see attached image:
![8960D80C-F43D-434A-BE1A-A2E8110682F4](https://user-images.githubusercontent.com/57045550/134765740-f893d5a9-3d81-4b7a-b443-c893f9faa23e.png)

**Comment by arvind0598** [comment]
Oh for sure. Thanks for the help! Let me know if you face any issues around sucky documentation or something.

**Comment by emmalearnscode** [comment]
Great, thanks. I’ll work on it this week.

**Comment by arvind0598** [comment]
Fixed in #14
